services:

  spark-base:
    build:
      context: ./spark
      dockerfile: Dockerfile
    image: spark:3.5.1

  spark-master:
    image: spark:3.5.1
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark/src:/opt/spark/app
      - ./spark/output:/opt/spark/output
      - ./data:/opt/spark/data
    depends_on:
      - spark-base
    command: >
      bash -c "
      /opt/spark/sbin/start-master.sh &&
      tail -f /dev/null
      "
    networks:
      - spark-net

  spark-worker-1:
    image: spark:3.5.1
    container_name: spark-worker-1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    volumes:
      - ./spark/output:/opt/spark/output
      - ./data:/opt/spark/data
    depends_on:
      - spark-master
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /dev/null
      "
    networks:
      - spark-net

  spark-worker-2:
    image: spark:3.5.1
    container_name: spark-worker-2
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    volumes:
      - ./spark/output:/opt/spark/output
      - ./data:/opt/spark/data
    depends_on:
      - spark-master
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /dev/null
      "
    networks:
      - spark-net

  spark-worker-3:
    image: spark:3.5.1
    container_name: spark-worker-3
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    volumes:
      - ./spark/output:/opt/spark/output
      - ./data:/opt/spark/data
    depends_on:
      - spark-master
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /dev/null
      "
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
